const nutrition = (amount, unit, calories, protein, carbs, fat) => ({
  amount,
  unit,
  calories,
  protein,
  carbs,
  fat,
});

const Ingredient = Object.freeze({
  GREEK_YOGURT: "greekYogurt",
  BANANA: "banana",
  BLUEBERRIES: "blueberries",
  ALMONDS: "almonds",
  ROTISSERIE_CHICKEN: "rotisserieChicken",
  FROZEN_CORN: "frozenCorn",
  CHIPOTLE_SAUCE: "chipotleSauce",
  ROMAINE_SALAD: "romaineSalad",
  MARINATED_CHICKEN_BREAST: "marinatedChickenBreast",
  JASMINE_RICE: "jasmineRice",
  BROCCOLI_FLORETS: "broccoliFlorets",
  EGGS: "eggs",
  WHOLE_WHEAT_TOAST: "wholeWheatToast",
  FLOUR_TORTILLA: "flourTortilla",
  CANNED_TUNA: "cannedTuna",
  SOURDOUGH_BREAD: "sourdoughBread",
  MAYO: "mayo",
  CUCUMBER: "cucumber",
  ROLLED_OATS: "rolledOats",
  HONEYCRISP_APPLE: "honeycrispApple",
  CAESAR_SALAD_KIT: "caesarSaladKit",
  DELI_TURKEY: "deliTurkey",
  COTTAGE_CHEESE: "cottageCheese",
  CHEDDAR_CHEESE: "cheddarCheese",
  PEANUT_BUTTER: "peanutButter",
  WHOLE_WHEAT_PITA: "wholeWheatPita",
  HUMMUS: "hummus",
  BABY_CARROTS: "babyCarrots",
  LENTIL_SOUP: "lentilSoup",
  GRANOLA: "granola",
  FROZEN_BURRITO_BOWL: "frozenBurritoBowl",
  SPINACH: "spinach",
  PLAIN_SKYR: "plainSkyr",
  ORANGE: "orange",
  APPLE: "apple",
  RASPBERRIES: "raspberries",
  STRAWBERRIES: "strawberries",
  WALNUTS: "walnuts",
  PUMPKIN_SEEDS: "pumpkinSeeds",
  GRILLED_CHICKEN_BREAST: "grilledChickenBreast",
  BLACK_BEANS: "blackBeans",
  FROZEN_PEAS: "frozenPeas",
  SALSA: "salsa",
  GREEK_YOGURT_RANCH: "greekYogurtRanch",
  SPRING_MIX: "springMix",
  CHICKEN_THIGHS: "chickenThighs",
  EXTRA_FIRM_TOFU: "extraFirmTofu",
  COOKED_BASMATI_RICE: "cookedBasmatiRice",
  COOKED_QUINOA: "cookedQuinoa",
  GREEN_BEANS: "greenBeans",
  ZUCCHINI: "zucchini",
  EGG_WHITES: "eggWhites",
  SOURDOUGH_TOAST: "sourdoughToast",
  ENGLISH_MUFFIN: "englishMuffin",
  WHOLE_WHEAT_TORTILLA: "wholeWheatTortilla",
  PITA: "pita",
  CANNED_SALMON: "cannedSalmon",
  CANNED_CHICKEN: "cannedChicken",
  WHOLE_WHEAT_BREAD: "wholeWheatBread",
  RYE_BREAD: "ryeBread",
  GREEK_YOGURT_CONDIMENT: "greekYogurtCondiment",
  MUSTARD: "mustard",
  CELERY: "celery",
  BELL_PEPPER: "bellPepper",
  PEAR: "pear",
  SOUTHWEST_SALAD_KIT: "southwestSaladKit",
  CHOPPED_GARDEN_SALAD_KIT: "choppedGardenSaladKit",
  DELI_CHICKEN: "deliChicken",
  ROAST_BEEF: "roastBeef",
  SWISS_CHEESE: "swissCheese",
  PROVOLONE: "provolone",
  ALMOND_BUTTER: "almondButter",
  SUNFLOWER_SEED_BUTTER: "sunflowerSeedButter",
  ROASTED_RED_PEPPER_HUMMUS: "roastedRedPepperHummus",
  TZATZIKI: "tzatziki",
  SNAP_PEAS: "snapPeas",
  BELL_PEPPER_STRIPS: "bellPepperStrips",
  CANNED_BLACK_BEAN_SOUP: "cannedBlackBeanSoup",
  CANNED_MINESTRONE: "cannedMinestrone",
  MUESLI: "muesli",
  BRAN_CEREAL: "branCereal",
  FROZEN_CHICKEN_FRIED_RICE: "frozenChickenFriedRice",
  FROZEN_VEGETABLE_CURRY_BOWL: "frozenVegetableCurryBowl",
  ARUGULA: "arugula",
  KALE: "kale",
});

const ingredientCatalog = Object.freeze({
  [Ingredient.GREEK_YOGURT]: {
    name: "plain Greek yogurt",
    category: "Dairy",
    groceryArea: "Refrigerated",
  },
  [Ingredient.BANANA]: {
    name: "banana",
    category: "Fruit",
    groceryArea: "Produce",
  },
  [Ingredient.BLUEBERRIES]: {
    name: "blueberries",
    category: "Fruit",
    groceryArea: "Produce",
  },
  [Ingredient.ALMONDS]: {
    name: "sliced almonds",
    category: "Pantry",
    groceryArea: "Pantry",
  },
  [Ingredient.ROTISSERIE_CHICKEN]: {
    name: "rotisserie chicken",
    category: "Protein",
    groceryArea: "Prepared foods",
  },
  [Ingredient.FROZEN_CORN]: {
    name: "frozen corn",
    category: "Vegetable",
    groceryArea: "Frozen",
  },
  [Ingredient.CHIPOTLE_SAUCE]: {
    name: "chipotle sauce",
    category: "Condiment",
    groceryArea: "Pantry",
  },
  [Ingredient.ROMAINE_SALAD]: {
    name: "romaine salad mix",
    category: "Vegetable",
    groceryArea: "Produce",
  },
  [Ingredient.MARINATED_CHICKEN_BREAST]: {
    name: "marinated chicken breast",
    category: "Protein",
    groceryArea: "Meat",
  },
  [Ingredient.JASMINE_RICE]: {
    name: "cooked jasmine rice",
    category: "Carb",
    groceryArea: "Pantry",
  },
  [Ingredient.BROCCOLI_FLORETS]: {
    name: "broccoli florets",
    category: "Vegetable",
    groceryArea: "Produce",
  },
  [Ingredient.EGGS]: {
    name: "eggs",
    category: "Protein",
    groceryArea: "Refrigerated",
  },
  [Ingredient.WHOLE_WHEAT_TOAST]: {
    name: "whole wheat toast",
    category: "Carb",
    groceryArea: "Bakery",
  },
  [Ingredient.FLOUR_TORTILLA]: {
    name: "large flour tortilla",
    category: "Carb",
    groceryArea: "Bakery",
  },
  [Ingredient.CANNED_TUNA]: {
    name: "canned tuna",
    category: "Protein",
    groceryArea: "Canned goods",
  },
  [Ingredient.SOURDOUGH_BREAD]: {
    name: "sourdough bread",
    category: "Carb",
    groceryArea: "Bakery",
  },
  [Ingredient.MAYO]: {
    name: "mayonnaise",
    category: "Condiment",
    groceryArea: "Pantry",
  },
  [Ingredient.CUCUMBER]: {
    name: "cucumber",
    category: "Vegetable",
    groceryArea: "Produce",
  },
  [Ingredient.ROLLED_OATS]: {
    name: "rolled oats",
    category: "Breakfast",
    groceryArea: "Pantry",
  },
  [Ingredient.HONEYCRISP_APPLE]: {
    name: "Honeycrisp apple",
    category: "Fruit",
    groceryArea: "Produce",
  },
  [Ingredient.CAESAR_SALAD_KIT]: {
    name: "Caesar salad kit",
    category: "Vegetable",
    groceryArea: "Produce",
  },
  [Ingredient.DELI_TURKEY]: {
    name: "deli turkey",
    category: "Protein",
    groceryArea: "Deli",
  },
  [Ingredient.COTTAGE_CHEESE]: {
    name: "cottage cheese",
    category: "Dairy",
    groceryArea: "Refrigerated",
  },
  [Ingredient.CHEDDAR_CHEESE]: {
    name: "cheddar cheese",
    category: "Dairy",
    groceryArea: "Refrigerated",
  },
  [Ingredient.PEANUT_BUTTER]: {
    name: "peanut butter",
    category: "Pantry",
    groceryArea: "Pantry",
  },
  [Ingredient.WHOLE_WHEAT_PITA]: {
    name: "whole wheat pita",
    category: "Carb",
    groceryArea: "Bakery",
  },
  [Ingredient.HUMMUS]: {
    name: "classic hummus",
    category: "Protein",
    groceryArea: "Refrigerated",
  },
  [Ingredient.BABY_CARROTS]: {
    name: "baby carrots",
    category: "Vegetable",
    groceryArea: "Produce",
  },
  [Ingredient.LENTIL_SOUP]: {
    name: "canned lentil soup",
    category: "Prepared meal",
    groceryArea: "Canned goods",
  },
  [Ingredient.GRANOLA]: {
    name: "granola",
    category: "Pantry",
    groceryArea: "Pantry",
  },
  [Ingredient.FROZEN_BURRITO_BOWL]: {
    name: "frozen burrito bowl",
    category: "Prepared meal",
    groceryArea: "Frozen",
  },
  [Ingredient.SPINACH]: {
    name: "baby spinach",
    category: "Vegetable",
    groceryArea: "Produce",
  },
  [Ingredient.PLAIN_SKYR]: {
    name: "plain skyr",
    category: "Dairy",
    groceryArea: "Refrigerated",
  },
  [Ingredient.ORANGE]: {
    name: "orange",
    category: "Fruit",
    groceryArea: "Produce",
  },
  [Ingredient.APPLE]: {
    name: "apple",
    category: "Fruit",
    groceryArea: "Produce",
  },
  [Ingredient.RASPBERRIES]: {
    name: "raspberries",
    category: "Fruit",
    groceryArea: "Produce",
  },
  [Ingredient.STRAWBERRIES]: {
    name: "strawberries",
    category: "Fruit",
    groceryArea: "Produce",
  },
  [Ingredient.WALNUTS]: {
    name: "walnuts",
    category: "Pantry",
    groceryArea: "Pantry",
  },
  [Ingredient.PUMPKIN_SEEDS]: {
    name: "pumpkin seeds",
    category: "Pantry",
    groceryArea: "Pantry",
  },
  [Ingredient.GRILLED_CHICKEN_BREAST]: {
    name: "grilled chicken breast",
    category: "Protein",
    groceryArea: "Meat",
  },
  [Ingredient.BLACK_BEANS]: {
    name: "black beans",
    category: "Protein",
    groceryArea: "Canned goods",
  },
  [Ingredient.FROZEN_PEAS]: {
    name: "frozen peas",
    category: "Vegetable",
    groceryArea: "Frozen",
  },
  [Ingredient.SALSA]: {
    name: "salsa",
    category: "Condiment",
    groceryArea: "Pantry",
  },
  [Ingredient.GREEK_YOGURT_RANCH]: {
    name: "Greek yogurt ranch",
    category: "Condiment",
    groceryArea: "Refrigerated",
  },
  [Ingredient.SPRING_MIX]: {
    name: "spring mix",
    category: "Vegetable",
    groceryArea: "Produce",
  },
  [Ingredient.CHICKEN_THIGHS]: {
    name: "chicken thighs",
    category: "Protein",
    groceryArea: "Meat",
  },
  [Ingredient.EXTRA_FIRM_TOFU]: {
    name: "extra-firm tofu",
    category: "Protein",
    groceryArea: "Refrigerated",
  },
  [Ingredient.COOKED_BASMATI_RICE]: {
    name: "cooked basmati rice",
    category: "Carb",
    groceryArea: "Pantry",
  },
  [Ingredient.COOKED_QUINOA]: {
    name: "cooked quinoa",
    category: "Carb",
    groceryArea: "Pantry",
  },
  [Ingredient.GREEN_BEANS]: {
    name: "green beans",
    category: "Vegetable",
    groceryArea: "Produce or frozen",
  },
  [Ingredient.ZUCCHINI]: {
    name: "zucchini",
    category: "Vegetable",
    groceryArea: "Produce",
  },
  [Ingredient.EGG_WHITES]: {
    name: "egg whites",
    category: "Protein",
    groceryArea: "Refrigerated",
  },
  [Ingredient.SOURDOUGH_TOAST]: {
    name: "sourdough toast",
    category: "Carb",
    groceryArea: "Bakery",
  },
  [Ingredient.ENGLISH_MUFFIN]: {
    name: "English muffin",
    category: "Carb",
    groceryArea: "Bakery",
  },
  [Ingredient.WHOLE_WHEAT_TORTILLA]: {
    name: "whole wheat tortilla",
    category: "Carb",
    groceryArea: "Bakery",
  },
  [Ingredient.PITA]: {
    name: "pita",
    category: "Carb",
    groceryArea: "Bakery",
  },
  [Ingredient.CANNED_SALMON]: {
    name: "canned salmon",
    category: "Protein",
    groceryArea: "Canned goods",
  },
  [Ingredient.CANNED_CHICKEN]: {
    name: "canned chicken",
    category: "Protein",
    groceryArea: "Canned goods",
  },
  [Ingredient.WHOLE_WHEAT_BREAD]: {
    name: "whole wheat bread",
    category: "Carb",
    groceryArea: "Bakery",
  },
  [Ingredient.RYE_BREAD]: {
    name: "rye bread",
    category: "Carb",
    groceryArea: "Bakery",
  },
  [Ingredient.GREEK_YOGURT_CONDIMENT]: {
    name: "Greek yogurt",
    category: "Dairy",
    groceryArea: "Refrigerated",
  },
  [Ingredient.MUSTARD]: {
    name: "mustard",
    category: "Condiment",
    groceryArea: "Pantry",
  },
  [Ingredient.CELERY]: {
    name: "celery",
    category: "Vegetable",
    groceryArea: "Produce",
  },
  [Ingredient.BELL_PEPPER]: {
    name: "bell pepper",
    category: "Vegetable",
    groceryArea: "Produce",
  },
  [Ingredient.PEAR]: {
    name: "pear",
    category: "Fruit",
    groceryArea: "Produce",
  },
  [Ingredient.SOUTHWEST_SALAD_KIT]: {
    name: "southwest salad kit",
    category: "Vegetable",
    groceryArea: "Produce",
  },
  [Ingredient.CHOPPED_GARDEN_SALAD_KIT]: {
    name: "chopped garden salad kit",
    category: "Vegetable",
    groceryArea: "Produce",
  },
  [Ingredient.DELI_CHICKEN]: {
    name: "deli chicken",
    category: "Protein",
    groceryArea: "Deli",
  },
  [Ingredient.ROAST_BEEF]: {
    name: "roast beef",
    category: "Protein",
    groceryArea: "Deli",
  },
  [Ingredient.SWISS_CHEESE]: {
    name: "Swiss cheese",
    category: "Dairy",
    groceryArea: "Refrigerated",
  },
  [Ingredient.PROVOLONE]: {
    name: "provolone",
    category: "Dairy",
    groceryArea: "Refrigerated",
  },
  [Ingredient.ALMOND_BUTTER]: {
    name: "almond butter",
    category: "Pantry",
    groceryArea: "Pantry",
  },
  [Ingredient.SUNFLOWER_SEED_BUTTER]: {
    name: "sunflower seed butter",
    category: "Pantry",
    groceryArea: "Pantry",
  },
  [Ingredient.ROASTED_RED_PEPPER_HUMMUS]: {
    name: "roasted red pepper hummus",
    category: "Protein",
    groceryArea: "Refrigerated",
  },
  [Ingredient.TZATZIKI]: {
    name: "tzatziki",
    category: "Dairy",
    groceryArea: "Refrigerated",
  },
  [Ingredient.SNAP_PEAS]: {
    name: "snap peas",
    category: "Vegetable",
    groceryArea: "Produce",
  },
  [Ingredient.BELL_PEPPER_STRIPS]: {
    name: "bell pepper strips",
    category: "Vegetable",
    groceryArea: "Produce",
  },
  [Ingredient.CANNED_BLACK_BEAN_SOUP]: {
    name: "canned black bean soup",
    category: "Prepared meal",
    groceryArea: "Canned goods",
  },
  [Ingredient.CANNED_MINESTRONE]: {
    name: "canned minestrone",
    category: "Prepared meal",
    groceryArea: "Canned goods",
  },
  [Ingredient.MUESLI]: {
    name: "muesli",
    category: "Pantry",
    groceryArea: "Pantry",
  },
  [Ingredient.BRAN_CEREAL]: {
    name: "bran cereal",
    category: "Pantry",
    groceryArea: "Pantry",
  },
  [Ingredient.FROZEN_CHICKEN_FRIED_RICE]: {
    name: "frozen chicken fried rice",
    category: "Prepared meal",
    groceryArea: "Frozen",
  },
  [Ingredient.FROZEN_VEGETABLE_CURRY_BOWL]: {
    name: "frozen vegetable curry bowl",
    category: "Prepared meal",
    groceryArea: "Frozen",
  },
  [Ingredient.ARUGULA]: {
    name: "arugula",
    category: "Vegetable",
    groceryArea: "Produce",
  },
  [Ingredient.KALE]: {
    name: "kale",
    category: "Vegetable",
    groceryArea: "Produce",
  },
});

const ingredientNutrition = Object.freeze({
  [Ingredient.GREEK_YOGURT]: nutrition(1, "cup", 130, 23, 9, 0),
  [Ingredient.BANANA]: nutrition(1, "", 105, 1, 27, 0),
  [Ingredient.BLUEBERRIES]: nutrition(0.5, "cup", 42, 1, 11, 0),
  [Ingredient.ALMONDS]: nutrition(2, "tbsp", 80, 3, 3, 7),
  [Ingredient.ROTISSERIE_CHICKEN]: nutrition(5, "oz", 260, 38, 0, 11),
  [Ingredient.FROZEN_CORN]: nutrition(0.5, "cup", 70, 2, 16, 1),
  [Ingredient.CHIPOTLE_SAUCE]: nutrition(2, "tbsp", 70, 1, 4, 6),
  [Ingredient.ROMAINE_SALAD]: nutrition(2, "cups", 20, 1, 4, 0),
  [Ingredient.MARINATED_CHICKEN_BREAST]: nutrition(6, "oz", 280, 50, 2, 7),
  [Ingredient.JASMINE_RICE]: nutrition(1, "cup", 205, 4, 45, 0),
  [Ingredient.BROCCOLI_FLORETS]: nutrition(2, "cups", 60, 5, 12, 1),
  [Ingredient.EGGS]: nutrition(1, "", 70, 6, 0, 5),
  [Ingredient.WHOLE_WHEAT_TOAST]: nutrition(1, "slice", 90, 4, 16, 1),
  [Ingredient.FLOUR_TORTILLA]: nutrition(1, "", 210, 6, 35, 5),
  [Ingredient.CANNED_TUNA]: nutrition(1, "can", 120, 26, 0, 1),
  [Ingredient.SOURDOUGH_BREAD]: nutrition(1, "slice", 110, 4, 22, 1),
  [Ingredient.MAYO]: nutrition(1, "tbsp", 90, 0, 0, 10),
  [Ingredient.CUCUMBER]: nutrition(1, "", 30, 1, 7, 0),
  [Ingredient.ROLLED_OATS]: nutrition(0.5, "cup", 150, 5, 27, 3),
  [Ingredient.HONEYCRISP_APPLE]: nutrition(1, "", 95, 0, 25, 0),
  [Ingredient.CAESAR_SALAD_KIT]: nutrition(1, "serving", 180, 5, 13, 13),
  [Ingredient.DELI_TURKEY]: nutrition(4, "oz", 120, 24, 2, 2),
  [Ingredient.COTTAGE_CHEESE]: nutrition(1, "cup", 220, 28, 8, 10),
  [Ingredient.CHEDDAR_CHEESE]: nutrition(1, "slice", 110, 7, 1, 9),
  [Ingredient.PEANUT_BUTTER]: nutrition(2, "tbsp", 190, 8, 7, 16),
  [Ingredient.WHOLE_WHEAT_PITA]: nutrition(1, "", 170, 6, 35, 2),
  [Ingredient.HUMMUS]: nutrition(0.33, "cup", 140, 5, 14, 8),
  [Ingredient.BABY_CARROTS]: nutrition(1, "cup", 50, 1, 12, 0),
  [Ingredient.LENTIL_SOUP]: nutrition(1, "can", 280, 16, 44, 4),
  [Ingredient.GRANOLA]: nutrition(0.33, "cup", 150, 4, 24, 5),
  [Ingredient.FROZEN_BURRITO_BOWL]: nutrition(1, "", 450, 18, 62, 15),
  [Ingredient.SPINACH]: nutrition(1, "cup", 7, 1, 1, 0),
  [Ingredient.PLAIN_SKYR]: nutrition(1, "cup", 150, 25, 11, 0),
  [Ingredient.ORANGE]: nutrition(1, "", 62, 1, 15, 0),
  [Ingredient.APPLE]: nutrition(1, "", 95, 0, 25, 0),
  [Ingredient.RASPBERRIES]: nutrition(0.5, "cup", 32, 1, 7, 0),
  [Ingredient.STRAWBERRIES]: nutrition(0.5, "cup", 25, 1, 6, 0),
  [Ingredient.WALNUTS]: nutrition(2, "tbsp", 95, 2, 2, 9),
  [Ingredient.PUMPKIN_SEEDS]: nutrition(2, "tbsp", 90, 5, 3, 7),
  [Ingredient.GRILLED_CHICKEN_BREAST]: nutrition(5, "oz", 230, 44, 0, 5),
  [Ingredient.BLACK_BEANS]: nutrition(0.5, "cup", 115, 8, 20, 1),
  [Ingredient.FROZEN_PEAS]: nutrition(0.5, "cup", 60, 4, 11, 0),
  [Ingredient.SALSA]: nutrition(2, "tbsp", 10, 0, 2, 0),
  [Ingredient.GREEK_YOGURT_RANCH]: nutrition(2, "tbsp", 45, 2, 2, 3),
  [Ingredient.SPRING_MIX]: nutrition(2, "cups", 15, 1, 3, 0),
  [Ingredient.CHICKEN_THIGHS]: nutrition(6, "oz", 360, 42, 0, 20),
  [Ingredient.EXTRA_FIRM_TOFU]: nutrition(6, "oz", 180, 20, 5, 10),
  [Ingredient.COOKED_BASMATI_RICE]: nutrition(1, "cup", 210, 4, 46, 0),
  [Ingredient.COOKED_QUINOA]: nutrition(1, "cup", 220, 8, 39, 4),
  [Ingredient.GREEN_BEANS]: nutrition(2, "cups", 70, 4, 16, 0),
  [Ingredient.ZUCCHINI]: nutrition(2, "cups", 40, 3, 7, 1),
  [Ingredient.EGG_WHITES]: nutrition(1, "", 17, 4, 0, 0),
  [Ingredient.SOURDOUGH_TOAST]: nutrition(1, "slice", 110, 4, 22, 1),
  [Ingredient.ENGLISH_MUFFIN]: nutrition(1, "", 130, 5, 25, 1),
  [Ingredient.WHOLE_WHEAT_TORTILLA]: nutrition(1, "", 190, 6, 32, 4),
  [Ingredient.PITA]: nutrition(1, "", 170, 6, 35, 2),
  [Ingredient.CANNED_SALMON]: nutrition(1, "can", 160, 23, 0, 7),
  [Ingredient.CANNED_CHICKEN]: nutrition(1, "can", 140, 30, 0, 2),
  [Ingredient.WHOLE_WHEAT_BREAD]: nutrition(1, "slice", 90, 4, 16, 1),
  [Ingredient.RYE_BREAD]: nutrition(1, "slice", 85, 3, 16, 1),
  [Ingredient.GREEK_YOGURT_CONDIMENT]: nutrition(1, "tbsp", 8, 1, 1, 0),
  [Ingredient.MUSTARD]: nutrition(1, "tbsp", 10, 1, 1, 0),
  [Ingredient.CELERY]: nutrition(1, "", 10, 0, 2, 0),
  [Ingredient.BELL_PEPPER]: nutrition(1, "", 30, 1, 7, 0),
  [Ingredient.PEAR]: nutrition(1, "", 100, 1, 27, 0),
  [Ingredient.SOUTHWEST_SALAD_KIT]: nutrition(1, "serving", 210, 6, 17, 14),
  [Ingredient.CHOPPED_GARDEN_SALAD_KIT]: nutrition(1, "serving", 150, 4, 14, 10),
  [Ingredient.DELI_CHICKEN]: nutrition(4, "oz", 120, 24, 2, 2),
  [Ingredient.ROAST_BEEF]: nutrition(4, "oz", 180, 28, 0, 7),
  [Ingredient.SWISS_CHEESE]: nutrition(1, "slice", 105, 8, 1, 8),
  [Ingredient.PROVOLONE]: nutrition(1, "slice", 100, 7, 1, 8),
  [Ingredient.ALMOND_BUTTER]: nutrition(2, "tbsp", 190, 7, 7, 17),
  [Ingredient.SUNFLOWER_SEED_BUTTER]: nutrition(2, "tbsp", 190, 7, 7, 16),
  [Ingredient.ROASTED_RED_PEPPER_HUMMUS]: nutrition(0.33, "cup", 140, 5, 14, 8),
  [Ingredient.TZATZIKI]: nutrition(0.33, "cup", 70, 4, 5, 4),
  [Ingredient.SNAP_PEAS]: nutrition(1, "cup", 40, 3, 7, 0),
  [Ingredient.BELL_PEPPER_STRIPS]: nutrition(1, "cup", 30, 1, 7, 0),
  [Ingredient.CANNED_BLACK_BEAN_SOUP]: nutrition(1, "can", 320, 18, 54, 4),
  [Ingredient.CANNED_MINESTRONE]: nutrition(1, "can", 220, 8, 38, 4),
  [Ingredient.MUESLI]: nutrition(0.33, "cup", 140, 5, 25, 3),
  [Ingredient.BRAN_CEREAL]: nutrition(0.33, "cup", 80, 3, 20, 1),
  [Ingredient.FROZEN_CHICKEN_FRIED_RICE]: nutrition(1, "", 430, 18, 58, 14),
  [Ingredient.FROZEN_VEGETABLE_CURRY_BOWL]: nutrition(1, "", 390, 12, 62, 11),
  [Ingredient.ARUGULA]: nutrition(1, "cup", 5, 1, 1, 0),
  [Ingredient.KALE]: nutrition(1, "cup", 35, 2, 7, 1),
});

const ingredientGramWeights = Object.freeze({
  [Ingredient.GREEK_YOGURT]: { cup: 245, tbsp: 15 },
  [Ingredient.BANANA]: { count: 126 },
  [Ingredient.BLUEBERRIES]: { cup: 148 },
  [Ingredient.ALMONDS]: { tbsp: 7 },
  [Ingredient.ROTISSERIE_CHICKEN]: { oz: 28.35 },
  [Ingredient.FROZEN_CORN]: { cup: 164 },
  [Ingredient.CHIPOTLE_SAUCE]: { tbsp: 15 },
  [Ingredient.ROMAINE_SALAD]: { cup: 47 },
  [Ingredient.MARINATED_CHICKEN_BREAST]: { oz: 28.35 },
  [Ingredient.JASMINE_RICE]: { cup: 158 },
  [Ingredient.BROCCOLI_FLORETS]: { cup: 91 },
  [Ingredient.EGGS]: { count: 50 },
  [Ingredient.WHOLE_WHEAT_TOAST]: { slice: 33 },
  [Ingredient.FLOUR_TORTILLA]: { count: 117 },
  [Ingredient.CANNED_TUNA]: { can: 85 },
  [Ingredient.SOURDOUGH_BREAD]: { slice: 28 },
  [Ingredient.MAYO]: { tbsp: 14 },
  [Ingredient.CUCUMBER]: { count: 300 },
  [Ingredient.ROLLED_OATS]: { cup: 80 },
  [Ingredient.HONEYCRISP_APPLE]: { count: 140 },
  [Ingredient.CAESAR_SALAD_KIT]: { serving: 100 },
  [Ingredient.DELI_TURKEY]: { oz: 28.35 },
  [Ingredient.COTTAGE_CHEESE]: { cup: 226, count: 110 },
  [Ingredient.CHEDDAR_CHEESE]: { slice: 28 },
  [Ingredient.PEANUT_BUTTER]: { tbsp: 16 },
  [Ingredient.WHOLE_WHEAT_PITA]: { count: 64 },
  [Ingredient.HUMMUS]: { cup: 246 },
  [Ingredient.BABY_CARROTS]: { cup: 128 },
  [Ingredient.LENTIL_SOUP]: { can: 567 },
  [Ingredient.GRANOLA]: { cup: 90 },
  [Ingredient.FROZEN_BURRITO_BOWL]: { count: 129 },
  [Ingredient.SPINACH]: { cup: 30 },
  [Ingredient.PLAIN_SKYR]: { cup: 245 },
  [Ingredient.ORANGE]: { count: 151 },
  [Ingredient.APPLE]: { count: 182 },
  [Ingredient.RASPBERRIES]: { cup: 123 },
  [Ingredient.STRAWBERRIES]: { cup: 152 },
  [Ingredient.WALNUTS]: { tbsp: 7.5 },
  [Ingredient.PUMPKIN_SEEDS]: { tbsp: 8 },
  [Ingredient.GRILLED_CHICKEN_BREAST]: { oz: 28.35 },
  [Ingredient.BLACK_BEANS]: { cup: 172 },
  [Ingredient.FROZEN_PEAS]: { cup: 160 },
  [Ingredient.SALSA]: { tbsp: 16 },
  [Ingredient.GREEK_YOGURT_RANCH]: { tbsp: 15 },
  [Ingredient.SPRING_MIX]: { cup: 35 },
  [Ingredient.CHICKEN_THIGHS]: { oz: 28.35 },
  [Ingredient.EXTRA_FIRM_TOFU]: { oz: 28.35 },
  [Ingredient.COOKED_BASMATI_RICE]: { cup: 158 },
  [Ingredient.COOKED_QUINOA]: { cup: 185 },
  [Ingredient.GREEN_BEANS]: { cup: 100 },
  [Ingredient.ZUCCHINI]: { cup: 124 },
  [Ingredient.EGG_WHITES]: { count: 33 },
  [Ingredient.SOURDOUGH_TOAST]: { slice: 29 },
  [Ingredient.ENGLISH_MUFFIN]: { slice: 57 },
  [Ingredient.WHOLE_WHEAT_TORTILLA]: { count: 41 },
  [Ingredient.PITA]: { count: 57 },
  [Ingredient.CANNED_SALMON]: { can: 170 },
  [Ingredient.CANNED_CHICKEN]: { can: 85 },
  [Ingredient.WHOLE_WHEAT_BREAD]: { slice: 36 },
  [Ingredient.RYE_BREAD]: { slice: 32 },
  [Ingredient.GREEK_YOGURT_CONDIMENT]: { tbsp: 15 },
  [Ingredient.MUSTARD]: { tbsp: 15 },
  [Ingredient.CELERY]: { count: 40 },
  [Ingredient.BELL_PEPPER]: { count: 150 },
  [Ingredient.PEAR]: { count: 178 },
  [Ingredient.SOUTHWEST_SALAD_KIT]: { serving: 100 },
  [Ingredient.CHOPPED_GARDEN_SALAD_KIT]: { serving: 344 },
  [Ingredient.DELI_CHICKEN]: { oz: 28.35 },
  [Ingredient.ROAST_BEEF]: { oz: 28.35 },
  [Ingredient.SWISS_CHEESE]: { slice: 28 },
  [Ingredient.PROVOLONE]: { slice: 28 },
  [Ingredient.ALMOND_BUTTER]: { tbsp: 16 },
  [Ingredient.SUNFLOWER_SEED_BUTTER]: { tbsp: 16 },
  [Ingredient.ROASTED_RED_PEPPER_HUMMUS]: { cup: 246 },
  [Ingredient.TZATZIKI]: { cup: 240 },
  [Ingredient.SNAP_PEAS]: { cup: 63 },
  [Ingredient.BELL_PEPPER_STRIPS]: { cup: 92 },
  [Ingredient.CANNED_BLACK_BEAN_SOUP]: { can: 257 },
  [Ingredient.CANNED_MINESTRONE]: { can: 298 },
  [Ingredient.MUESLI]: { cup: 85 },
  [Ingredient.BRAN_CEREAL]: { cup: 59 },
  [Ingredient.FROZEN_CHICKEN_FRIED_RICE]: { count: 340 },
  [Ingredient.FROZEN_VEGETABLE_CURRY_BOWL]: { count: 200 },
  [Ingredient.ARUGULA]: { cup: 20 },
  [Ingredient.KALE]: { cup: 21 },
});
